language: c

sudo: false

addons:
  apt:
    packages:
      - tcl
      - tcl-dev
      - apache2-dev
      - apache2

cache:
  - apt
  
script:
 - cd src/unix
 - autoconf
 - ./configure --enable-thread --with-tclinclude=/usr/include/tcl --with-tcl=/usr/lib
 - make
 - make test
